server:
  port: 8083

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        connection:
          dialect: org.hibernate.dialect.PostgreSQL95Dialect
  datasource:
    password: 28072004
    username: postgres
    url: jdbc:postgresql://localhost:5432/tg_bot
  rabbitmq:
    host: localhost
    username: userok
    password: p@ssw0rd